// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI/migrate runs against a local SQLite file only. The hosted Turso DB
    // can't be reached by `prisma migrate` (no driver-adapter hook in this
    // Prisma version) — apply prisma/migrations/*/migration.sql there via
    // `turso db shell <db> < migration.sql` instead.
    url: process.env["DATABASE_URL"],
  },
});
